### ISSUE TITLE
CSS is broken in some docs

### ISSUE THREAD

**Issue by nashamri** [syl20bnr/develop.spacemacs.org#1]
Like in here:
http://develop.spacemacs.org/layers/+pair-programming/floobits/README.html
and
http://develop.spacemacs.org/layers/+lang/csv/README.html
and
http://develop.spacemacs.org/layers/+web-services/twitter/README.html

It could be just the new layers.

**Comment by syl20bnr** [comment]
Fixed thanks to the awesome work of @JAremko :tada:
