### ISSUE TITLE
TOC entries with same name linked incorrectly

### ISSUE THREAD

**Issue by laerling** [syl20bnr/develop.spacemacs.org#10]
When going to e. g. [header 3.5. 'use-package' in the layers doc](http://spacemacs.org/doc/LAYERS.html#use-package) there is also header 7.2. with the same name.

1. Header 7.2. is expanded in the TOC when visiting 3.5. and vice versa.
2. When clicking on 7.2. in the TOC it directs to 3.5. I guess it just searches for the header name.

**Comment by syl20bnr** [comment]
Should be fixed when we regenerate the docs.

**Comment by JAremko** [comment]
`toc-org` simply adds `-N` to a link each time it repeats. i.e `use-package` `use-package-1` `use-package-2`  I think we should do the same.

**Comment by syl20bnr** [comment]
Thank you for the report.
Fixed in `develop.spacemacs.org` will be merged to `spacemacs.org` at next major release.
