### ISSUE TITLE
(spacemacs) Тоо lispy

### ISSUE THREAD

**Issue by JAremko** [syl20bnr/develop.spacemacs.org#3]
I noticed that http://develop.spacemacs.org/ has `(spacemacs)` instead of `Spacemacs_` Not sure what `_` stands for(console cursor?), but the round brackets are kinda scream lisp, reinforcing the fear in the newcomers that since Spacemacs is based on Emacs it means you need some kind of knowledge of lisp to use it(and it's not true.)

_But that's just my two cents._ :wink:

**Comment by nashamri** [comment]
We are trying to scare away people with parens :smile: j/k
and you are right about the `_`, it was meant to be a console cursor.

**Comment by JAremko** [comment]
Then you should go with (((spacemacs))) :stuck_out_tongue_winking_eye:

**Comment by JAremko** [comment]
> We are trying to scare away <s>people</s> unworthy with parens :smile: j/k   

**FTFY**

**Comment by syl20bnr** [comment]
We assume the power of lisp, the parenthesis are part of the "branding" :-)

**Comment by JAremko** [comment]
One day someone will get a tattoo with it. So It's better be good :shipit:

**Comment by nashamri** [comment]
@JAremko @syl20bnr I think the parenthesis are very suitable for the cult of spacemacs :smile: 
![sketch66201557](https://cloud.githubusercontent.com/assets/1207107/17458276/faa434e4-5bb8-11e6-9643-2ec640b9c2e9.png)

**Comment by JAremko** [comment]
+1 Also we need a covenant of some kind. And make adepts swear a solemn vow.  

_Not sure if a bit over the top, but forehead branding like in Game of Thrones would be cool._
